<?php

use Drupal\Core\Form\FormStateInterface;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function customwebform_form_alter(&$form,$form_state,$form_id){
    
    if($form_id == 'webform_submission_new_test_form_add_form'){ 
        $form['terms'] = array(
        '#type' => 'checkbox',
        '#title' => t("I accept the website's terms."),
        '#required' => TRUE,
        );
       $form['actions']['submit']['#submit'][] = 'submitWebform';
    }
}

function submitWebform(array &$form,FormStateInterface $form_state){
    $contact_details = $form_state->getvalue('contact_details');
    db_insert('customwebform')
        ->fields(array(
            'name' => $form_state->getValue('name'),
            'email' => $contact_details['email'],
            'mobilenumber'=> $form_state->getValue('phone'),
            'company'=>$contact_details['company'],
            'city'=>$contact_details['city'],
            'address'=>$contact_details['address'],
        ))
        ->execute(); 
}