<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function mydata_theme() {
  return [
    'my_custom_form' => [
      'render element' => 'form',
    ],
  ];
}




/**
 * Get the children of a menu item in a given menu.
 *
 * @param string $title
 *   The title of the parent menu item.
 * @param string $menu
 *   The internal menu name.
 * 
 * @return array
 *   The children of the given parent. 
 */
function mydata_submenu_tree_all_data($title, $menu = 'reports') {
  $tree = menu_tree_all_data($menu);
  foreach ($tree as $branch) {
    if ($branch['link']['title'] == $title) {
      return $branch['below'];
    }
  }
  return array();
}


//function mydata_form_alter(&$form,$form_state,$form_id){
//    if($form_id = 'webform_submission_new_test_form_add_form'){
//        echo "hii";exit();
//    }
//}

function mydata_preprocess(&$variables, $hook){
//    kint($hook);
    if($hook == 'menu'){
        foreach($variables['items'] as  &$items ){
            $items['title'] = $items['title']. 'en';
        }
    }
}